<?php

/**
 * BaseTicket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $event_id
 * @property integer $type
 * @property float $price
 * @property integer $max
 * @property integer $min
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property integer $quantity_available
 * @property integer $quantity_sold
 * @property boolean $visible
 * @property integer $eventbrite_id
 * @property Event $Event
 * 
 * @method integer   getEventId()            Returns the current record's "event_id" value
 * @method integer   getType()               Returns the current record's "type" value
 * @method float     getPrice()              Returns the current record's "price" value
 * @method integer   getMax()                Returns the current record's "max" value
 * @method integer   getMin()                Returns the current record's "min" value
 * @method timestamp getStartDate()          Returns the current record's "start_date" value
 * @method timestamp getEndDate()            Returns the current record's "end_date" value
 * @method integer   getQuantityAvailable()  Returns the current record's "quantity_available" value
 * @method integer   getQuantitySold()       Returns the current record's "quantity_sold" value
 * @method boolean   getVisible()            Returns the current record's "visible" value
 * @method integer   getEventbriteId()       Returns the current record's "eventbrite_id" value
 * @method Event     getEvent()              Returns the current record's "Event" value
 * @method Ticket    setEventId()            Sets the current record's "event_id" value
 * @method Ticket    setType()               Sets the current record's "type" value
 * @method Ticket    setPrice()              Sets the current record's "price" value
 * @method Ticket    setMax()                Sets the current record's "max" value
 * @method Ticket    setMin()                Sets the current record's "min" value
 * @method Ticket    setStartDate()          Sets the current record's "start_date" value
 * @method Ticket    setEndDate()            Sets the current record's "end_date" value
 * @method Ticket    setQuantityAvailable()  Sets the current record's "quantity_available" value
 * @method Ticket    setQuantitySold()       Sets the current record's "quantity_sold" value
 * @method Ticket    setVisible()            Sets the current record's "visible" value
 * @method Ticket    setEventbriteId()       Sets the current record's "eventbrite_id" value
 * @method Ticket    setEvent()              Sets the current record's "Event" value
 * 
 * @package    toaberlin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTicket extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ticket');
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('price', 'float', 4, array(
             'type' => 'float',
             'length' => 4,
             'scale' => '2',
             ));
        $this->hasColumn('max', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('min', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('quantity_available', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('quantity_sold', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('eventbrite_id', 'integer', 16, array(
             'type' => 'integer',
             'length' => 16,
             ));

        $this->option('charset', 'UTF8');
        $this->option('type', 'innodb');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));
    }
}