<?php

/**
 * BaseAttendee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property boolean $has_main_ticket
 * @property sfGuardUser $GuardUser
 * @property Doctrine_Collection $Tickets
 * @property Doctrine_Collection $AttendeeTickets
 * 
 * @method integer             getUserId()          Returns the current record's "user_id" value
 * @method boolean             getHasMainTicket()   Returns the current record's "has_main_ticket" value
 * @method sfGuardUser         getGuardUser()       Returns the current record's "GuardUser" value
 * @method Doctrine_Collection getTickets()         Returns the current record's "Tickets" collection
 * @method Doctrine_Collection getAttendeeTickets() Returns the current record's "AttendeeTickets" collection
 * @method Attendee            setUserId()          Sets the current record's "user_id" value
 * @method Attendee            setHasMainTicket()   Sets the current record's "has_main_ticket" value
 * @method Attendee            setGuardUser()       Sets the current record's "GuardUser" value
 * @method Attendee            setTickets()         Sets the current record's "Tickets" collection
 * @method Attendee            setAttendeeTickets() Sets the current record's "AttendeeTickets" collection
 * 
 * @package    toaberlin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAttendee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attendee');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('has_main_ticket', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));

        $this->option('charset', 'UTF8');
        $this->option('type', 'innodb');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as GuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Ticket as Tickets', array(
             'refClass' => 'AttendeeTicket',
             'local' => 'attendee_id',
             'foreign' => 'ticket_id'));

        $this->hasMany('AttendeeTicket as AttendeeTickets', array(
             'local' => 'id',
             'foreign' => 'attendee_id'));
    }
}