<?php

/**
 * BaseProgram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $position
 * @property string $company
 * @property string $description
 * @property string $url
 * @property string $facebook
 * @property string $twitter
 * 
 * @method string  getFirstName()   Returns the current record's "first_name" value
 * @method string  getLastName()    Returns the current record's "last_name" value
 * @method string  getPosition()    Returns the current record's "position" value
 * @method string  getCompany()     Returns the current record's "company" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method string  getUrl()         Returns the current record's "url" value
 * @method string  getFacebook()    Returns the current record's "facebook" value
 * @method string  getTwitter()     Returns the current record's "twitter" value
 * @method Program setFirstName()   Sets the current record's "first_name" value
 * @method Program setLastName()    Sets the current record's "last_name" value
 * @method Program setPosition()    Sets the current record's "position" value
 * @method Program setCompany()     Sets the current record's "company" value
 * @method Program setDescription() Sets the current record's "description" value
 * @method Program setUrl()         Sets the current record's "url" value
 * @method Program setFacebook()    Sets the current record's "facebook" value
 * @method Program setTwitter()     Sets the current record's "twitter" value
 * 
 * @package    toaberlin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProgram extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('program');
        $this->hasColumn('first_name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('last_name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('position', 'string', 48, array(
             'type' => 'string',
             'length' => 48,
             ));
        $this->hasColumn('company', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('description', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('url', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('facebook', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('twitter', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));

        $this->option('charset', 'UTF8');
        $this->option('type', 'innodb');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}