<?php

/**
 * BaseVenue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $address
 * @property string $city
 * @property integer $postal_code
 * @property float $longitude
 * @property float $latitude
 * @property integer $eventbrite_id
 * @property Doctrine_Collection $Events
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getAddress()       Returns the current record's "address" value
 * @method string              getCity()          Returns the current record's "city" value
 * @method integer             getPostalCode()    Returns the current record's "postal_code" value
 * @method float               getLongitude()     Returns the current record's "longitude" value
 * @method float               getLatitude()      Returns the current record's "latitude" value
 * @method integer             getEventbriteId()  Returns the current record's "eventbrite_id" value
 * @method Doctrine_Collection getEvents()        Returns the current record's "Events" collection
 * @method Venue               setName()          Sets the current record's "name" value
 * @method Venue               setAddress()       Sets the current record's "address" value
 * @method Venue               setCity()          Sets the current record's "city" value
 * @method Venue               setPostalCode()    Sets the current record's "postal_code" value
 * @method Venue               setLongitude()     Sets the current record's "longitude" value
 * @method Venue               setLatitude()      Sets the current record's "latitude" value
 * @method Venue               setEventbriteId()  Sets the current record's "eventbrite_id" value
 * @method Venue               setEvents()        Sets the current record's "Events" collection
 * 
 * @package    toaberlin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVenue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('venue');
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('address', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('city', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('postal_code', 'integer', 6, array(
             'type' => 'integer',
             'length' => 6,
             ));
        $this->hasColumn('longitude', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('latitude', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('eventbrite_id', 'integer', 16, array(
             'type' => 'integer',
             'length' => 16,
             ));

        $this->option('charset', 'UTF8');
        $this->option('type', 'innodb');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Event as Events', array(
             'local' => 'id',
             'foreign' => 'venue_id'));
    }
}