<?php

/**
 * BaseEventTicket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $event_id
 * @property integer $ticket_id
 * 
 * @method integer     getEventId()   Returns the current record's "event_id" value
 * @method integer     getTicketId()  Returns the current record's "ticket_id" value
 * @method EventTicket setEventId()   Sets the current record's "event_id" value
 * @method EventTicket setTicketId()  Sets the current record's "ticket_id" value
 * 
 * @package    toaberlin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventTicket extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_ticket');
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('ticket_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('charset', 'UTF8');
        $this->option('type', 'innodb');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}