<?php

/**
 * Attendee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    toaberlin
 * @subpackage model
 * @author     maciej@canadel.ee
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Attendee extends BaseAttendee {

	public function checkForMainTicket() {

		// TODO: check for main ticket rrrrrrrrrright here amigo! ;)

	}
}
