<?php

/**
 * Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    toaberlin
 * @subpackage model
 * @author     maciej@canadel.ee
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Event extends BaseEvent {

	public function getStartHour() {

		return date('H:i', strtotime($this->getStartDate()));
	}
	public function getEndHour() {

		return date('H:i', strtotime($this->getEndDate()));
	}
	public function toggleModerated() {

		$this->setModerated($this->getModerated() ? false : true);
		$this->save();
	}
	public function sendEventToAPI() {

		// TODO: remember to push privacy and and status as 1
	}
}
