<?php

/**
 * EventTicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTicketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTicketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventTicket');
    }
}