<?php

/**
 * OrganiserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganiserTable extends Doctrine_Table {

	public static function getInstance() { return Doctrine_Core::getTable('Organiser'); }

	public function getUnsynchronized() {

		// base query
		$q = $this->createQuery()

			->from('Organiser o')
			->where('o.test = ?', false)
			->addWhere('o.synchronized = ?', false)
		;

		return $q->execute();
	}
}
