<?php

/**
 * OrganiserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganiserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganiserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Organiser');
    }
}