<?php

/**
 * Press
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    toaberlin
 * @subpackage model
 * @author     maciej@canadel.ee
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Press extends BasePress {

	public function getDateHtmlFormatted() {

		if(!is_null($this->getDate())) {

			$timestamp = strtotime($this->getDate());

			return sprintf('%s<sup>%s</sup>, %s - ',

				date('M j', $timestamp),
				date('S', $timestamp),
				date('Y', $timestamp)
			);
		}
		else return null;
	}
}
