<?php

/**
 * PressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressTable extends Doctrine_Table {

	public static function getInstance() { return Doctrine_Core::getTable('Press'); }

	public function getWithPosition(Doctrine_Query $q) {

		$r = $q->getRootAlias();
		$q->orderBy($r . '.position');
		return $q;
	}
}
