<?php

/**
 * ProgramSpeakerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgramSpeakerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgramSpeakerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProgramSpeaker');
    }
}