<?php

/**
 * ProgramModeratorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgramModeratorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgramModeratorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProgramModerator');
    }
}