<?php

/**
 * UserTicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTicketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTicketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserTicket');
    }
}