<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/05/21 23:16:59
sfConfig::add(array(
  'app_oauth_key' => 'DZ3QWRJQG75Z2K7QQ7',
  'app_oauth_secret' => '5JSC5HEBQQIPAL7SBWOQQ3XME3CKGYSDK7NMTJAJLJOSEFO7UP',
));
