<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/05/21 23:17:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=toaberlin_sf',
  'username' => 'root',
  'password' => 'lorane921',
  'name' => 'doctrine',
)),);
