<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('speaker', 'company', 'string', '64', array(
             ));
    }

    public function down()
    {

    }
}