<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('program_speaker', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'program_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'speaker_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             ), array(
             'type' => 'innodb',
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
        $this->createTable('speaker', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'face' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'company' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '512',
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'facebook' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'twitter' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'innodb',
             'indexes' => 
             array(
              'speaker_position_sortable' => 
              array(
              'fields' => 
              array(
               0 => 'position',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
        $this->removeColumn('program', 'first_name');
        $this->removeColumn('program', 'last_name');
        $this->removeColumn('program', 'position');
        $this->removeColumn('program', 'company');
        $this->removeColumn('program', 'url');
        $this->removeColumn('program', 'facebook');
        $this->removeColumn('program', 'twitter');
        $this->addColumn('program', 'kind', 'string', '32', array(
             ));
        $this->addColumn('program', 'title', 'string', '64', array(
             ));
        $this->addColumn('program', 'start_hour', 'time', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('program', 'end_hour', 'time', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('program_speaker');
        $this->dropTable('speaker');
        $this->addColumn('program', 'first_name', 'string', '64', array(
             ));
        $this->addColumn('program', 'last_name', 'string', '64', array(
             ));
        $this->addColumn('program', 'position', 'string', '48', array(
             ));
        $this->addColumn('program', 'company', 'string', '32', array(
             ));
        $this->addColumn('program', 'url', 'string', '128', array(
             ));
        $this->addColumn('program', 'facebook', 'string', '128', array(
             ));
        $this->addColumn('program', 'twitter', 'string', '128', array(
             ));
        $this->removeColumn('program', 'kind');
        $this->removeColumn('program', 'title');
        $this->removeColumn('program', 'start_hour');
        $this->removeColumn('program', 'end_hour');
    }
}