<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('press', 'url', 'string', '192', array(
             ));
    }

    public function down()
    {

    }
}