<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('speaker', 'company_position', 'string', '96', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('speaker', 'company_position');
    }
}