<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('program_moderator', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'program_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'speaker_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             ), array(
             'type' => 'innodb',
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
        $this->addColumn('program', 'photo', 'string', '128', array(
             ));
        $this->addColumn('program', 'url', 'string', '128', array(
             ));
        $this->addColumn('program', 'facebook', 'string', '128', array(
             ));
        $this->addColumn('program', 'twitter', 'string', '128', array(
             ));
        $this->addColumn('program', 'room', 'string', '32', array(
             ));
    }

    public function down()
    {
        $this->dropTable('program_moderator');
        $this->removeColumn('program', 'photo');
        $this->removeColumn('program', 'url');
        $this->removeColumn('program', 'facebook');
        $this->removeColumn('program', 'twitter');
        $this->removeColumn('program', 'room');
    }
}