<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('program_moderator', 'program_moderator_program_id_program_id');
        $this->dropForeignKey('program_moderator', 'program_moderator_speaker_id_speaker_id');
        $this->dropForeignKey('program_speaker', 'program_speaker_program_id_program_id');
        $this->dropForeignKey('program_speaker', 'program_speaker_speaker_id_speaker_id');
        $this->createForeignKey('program_moderator', 'program_moderator_program_id_program_id_1', array(
             'name' => 'program_moderator_program_id_program_id_1',
             'local' => 'program_id',
             'foreign' => 'id',
             'foreignTable' => 'program',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('program_moderator', 'program_moderator_speaker_id_speaker_id_1', array(
             'name' => 'program_moderator_speaker_id_speaker_id_1',
             'local' => 'speaker_id',
             'foreign' => 'id',
             'foreignTable' => 'speaker',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('program_speaker', 'program_speaker_program_id_program_id_1', array(
             'name' => 'program_speaker_program_id_program_id_1',
             'local' => 'program_id',
             'foreign' => 'id',
             'foreignTable' => 'program',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('program_speaker', 'program_speaker_speaker_id_speaker_id_1', array(
             'name' => 'program_speaker_speaker_id_speaker_id_1',
             'local' => 'speaker_id',
             'foreign' => 'id',
             'foreignTable' => 'speaker',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('program_moderator', 'program_moderator_program_id', array(
             'fields' => 
             array(
              0 => 'program_id',
             ),
             ));
        $this->addIndex('program_moderator', 'program_moderator_speaker_id', array(
             'fields' => 
             array(
              0 => 'speaker_id',
             ),
             ));
        $this->addIndex('program_speaker', 'program_speaker_program_id', array(
             'fields' => 
             array(
              0 => 'program_id',
             ),
             ));
        $this->addIndex('program_speaker', 'program_speaker_speaker_id', array(
             'fields' => 
             array(
              0 => 'speaker_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('program_moderator', 'program_moderator_program_id_program_id', array(
             'name' => 'program_moderator_program_id_program_id',
             'local' => 'program_id',
             'foreign' => 'id',
             'foreignTable' => 'program',
             ));
        $this->createForeignKey('program_moderator', 'program_moderator_speaker_id_speaker_id', array(
             'name' => 'program_moderator_speaker_id_speaker_id',
             'local' => 'speaker_id',
             'foreign' => 'id',
             'foreignTable' => 'speaker',
             ));
        $this->createForeignKey('program_speaker', 'program_speaker_program_id_program_id', array(
             'name' => 'program_speaker_program_id_program_id',
             'local' => 'program_id',
             'foreign' => 'id',
             'foreignTable' => 'program',
             ));
        $this->createForeignKey('program_speaker', 'program_speaker_speaker_id_speaker_id', array(
             'name' => 'program_speaker_speaker_id_speaker_id',
             'local' => 'speaker_id',
             'foreign' => 'id',
             'foreignTable' => 'speaker',
             ));
        $this->dropForeignKey('program_moderator', 'program_moderator_program_id_program_id_1');
        $this->dropForeignKey('program_moderator', 'program_moderator_speaker_id_speaker_id_1');
        $this->dropForeignKey('program_speaker', 'program_speaker_program_id_program_id_1');
        $this->dropForeignKey('program_speaker', 'program_speaker_speaker_id_speaker_id_1');
        $this->removeIndex('program_moderator', 'program_moderator_program_id', array(
             'fields' => 
             array(
              0 => 'program_id',
             ),
             ));
        $this->removeIndex('program_moderator', 'program_moderator_speaker_id', array(
             'fields' => 
             array(
              0 => 'speaker_id',
             ),
             ));
        $this->removeIndex('program_speaker', 'program_speaker_program_id', array(
             'fields' => 
             array(
              0 => 'program_id',
             ),
             ));
        $this->removeIndex('program_speaker', 'program_speaker_speaker_id', array(
             'fields' => 
             array(
              0 => 'speaker_id',
             ),
             ));
    }
}
