<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('program', 'description', 'string', '4096', array(
             ));
        $this->changeColumn('speaker', 'description', 'string', '4096', array(
             ));
    }

    public function down()
    {

    }
}